# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parallelLOF <- function(data, k, equal_num) {
    .Call('process_parallelLOF', PACKAGE = 'process', data, k, equal_num)
}

TrimSum <- function(A, p, r, K) {
    .Call('process_TrimSum', PACKAGE = 'process', A, p, r, K)
}

TrimMean <- function(A, p, r, K) {
    .Call('process_TrimMean', PACKAGE = 'process', A, p, r, K)
}

test <- function(A, p, r, K) {
    .Call('process_test', PACKAGE = 'process', A, p, r, K)
}

